-- begin PIZZAPLACE_CUSTOMER
create unique index IDX_PIZZAPLACE_CUSTOMER_UNIQ_EMAIL on PIZZAPLACE_CUSTOMER (EMAIL) ^
-- end PIZZAPLACE_CUSTOMER
-- begin PIZZAPLACE_INGREDIENTS
create unique index IDX_PIZZAPLACE_INGREDIENTS_UNIQ_NAME on PIZZAPLACE_INGREDIENTS (NAME) ^
-- end PIZZAPLACE_INGREDIENTS
-- begin PIZZAPLACE_ORDER
alter table PIZZAPLACE_ORDER add constraint FK_PIZZAPLACE_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references PIZZAPLACE_CUSTOMER(ID)^
create index IDX_PIZZAPLACE_ORDER_ON_CUSTOMER on PIZZAPLACE_ORDER (CUSTOMER_ID)^
-- end PIZZAPLACE_ORDER
-- begin PIZZAPLACE_DISH_TYPE
create unique index IDX_PIZZAPLACE_DISH_TYPE_UNIQ_NAME on PIZZAPLACE_DISH_TYPE (NAME) ^
-- end PIZZAPLACE_DISH_TYPE
-- begin PIZZAPLACE_DISH
alter table PIZZAPLACE_DISH add constraint FK_PIZZAPLACE_DISH_ON_DISH_TYPE foreign key (DISH_TYPE_ID) references PIZZAPLACE_DISH_TYPE(ID)^
create unique index IDX_PIZZAPLACE_DISH_UNIQ_NAME on PIZZAPLACE_DISH (NAME) ^
create index IDX_PIZZAPLACE_DISH_ON_DISH_TYPE on PIZZAPLACE_DISH (DISH_TYPE_ID)^
-- end PIZZAPLACE_DISH
-- begin PIZZAPLACE_ORDER_DISH_LINK
alter table PIZZAPLACE_ORDER_DISH_LINK add constraint FK_ORDDIS_ON_DISH foreign key (DISH_ID) references PIZZAPLACE_DISH(ID)^
alter table PIZZAPLACE_ORDER_DISH_LINK add constraint FK_ORDDIS_ON_ORDER foreign key (ORDER_ID) references PIZZAPLACE_ORDER(ID)^
-- end PIZZAPLACE_ORDER_DISH_LINK
-- begin PIZZAPLACE_DISH_INGREDIENTS_LINK
alter table PIZZAPLACE_DISH_INGREDIENTS_LINK add constraint FK_DISING_ON_DISH foreign key (DISH_ID) references PIZZAPLACE_DISH(ID)^
alter table PIZZAPLACE_DISH_INGREDIENTS_LINK add constraint FK_DISING_ON_INGREDIENTS foreign key (INGREDIENTS_ID) references PIZZAPLACE_INGREDIENTS(ID)^
-- end PIZZAPLACE_DISH_INGREDIENTS_LINK
-- begin PIZZAPLACE_DISH_QUANTITY
alter table PIZZAPLACE_DISH_QUANTITY add constraint FK_PIZZAPLACE_DISH_QUANTITY_ON_DISH foreign key (DISH_ID) references PIZZAPLACE_DISH(ID)^
alter table PIZZAPLACE_DISH_QUANTITY add constraint FK_PIZZAPLACE_DISH_QUANTITY_ON_ORDER foreign key (ORDER_ID) references PIZZAPLACE_ORDER(ID)^
create index IDX_PIZZAPLACE_DISH_QUANTITY_ON_DISH on PIZZAPLACE_DISH_QUANTITY (DISH_ID)^
create index IDX_PIZZAPLACE_DISH_QUANTITY_ON_ORDER on PIZZAPLACE_DISH_QUANTITY (ORDER_ID)^
-- end PIZZAPLACE_DISH_QUANTITY
