alter table PIZZAPLACE_ORDER alter column DELIVERED_ID rename to DELIVERED_ID__U07539 ^
drop index IDX_PIZZAPLACE_ORDER_ON_DELIVERED ;
alter table PIZZAPLACE_ORDER drop constraint FK_PIZZAPLACE_ORDER_ON_DELIVERED ;
