alter table PIZZAPLACE_ORDER alter column DELIVERED_ID rename to DELIVERED_ID__U54695 ^
drop index IDX_PIZZAPLACE_ORDER_ON_DELIVERED ;
drop index IDX_PIZZAPLACE_ORDER_UNIQ_DELIVERED_ID ;
alter table PIZZAPLACE_ORDER drop constraint FK_PIZZAPLACE_ORDER_ON_DELIVERED ;
