alter table PIZZAPLACE_DISH_QUANTITY add constraint FK_PIZZAPLACE_DISH_QUANTITY_ON_DISH foreign key (DISH_ID) references PIZZAPLACE_DISH(ID);
alter table PIZZAPLACE_DISH_QUANTITY add constraint FK_PIZZAPLACE_DISH_QUANTITY_ON_ORDER foreign key (ORDER_ID) references PIZZAPLACE_ORDER(ID);
create index IDX_PIZZAPLACE_DISH_QUANTITY_ON_DISH on PIZZAPLACE_DISH_QUANTITY (DISH_ID);
create index IDX_PIZZAPLACE_DISH_QUANTITY_ON_ORDER on PIZZAPLACE_DISH_QUANTITY (ORDER_ID);
