alter table PIZZAPLACE_DELIVERED alter column ORDER_ID rename to ORDER_ID__U94969 ^
alter table PIZZAPLACE_DELIVERED alter column ORDER_ID__U94969 set null ;
drop index IDX_PIZZAPLACE_DELIVERED_UNIQ_ORDER_ID ;
drop index IDX_PIZZAPLACE_DELIVERED_ON_ORDER ;
alter table PIZZAPLACE_DELIVERED drop constraint FK_PIZZAPLACE_DELIVERED_ON_ORDER ;
