alter table PIZZAPLACE_DISH add constraint FK_PIZZAPLACE_DISH_ON_DISH_PHOTO foreign key (DISH_PHOTO_ID) references SYS_FILE(ID);
create index IDX_PIZZAPLACE_DISH_ON_DISH_PHOTO on PIZZAPLACE_DISH (DISH_PHOTO_ID);
