alter table PIZZAPLACE_DELIVERED add constraint FK_PIZZAPLACE_DELIVERED_ON_ORDER foreign key (ORDER_ID) references PIZZAPLACE_ORDER(ID);
create index IDX_PIZZAPLACE_DELIVERED_ON_ORDER on PIZZAPLACE_DELIVERED (ORDER_ID);
